# YAML config for dataset, training, and model parameters

# Dataset parameters
dataset:
  n_links_max: 100
  shard: 0
  lr: 10
  n_samples_sampled: 4000
  threadhold_sampled: 150
  train_frac: 0.9
  topo_type: "_topology_flows"
  sampling_method: "balanced" # weighted, uniform, balanced
  flow_size_threshold: 100000000
  enable_flowsim_gt: False
  enable_remainsize: False
  enable_queuelen: False
  enable_testbed: True

# Model parameters
model:
  input_size: 2
  n_layer: 2
  gcn_n_layer: 3
  loss_fn_type: "l1"
  hidden_size: 200
  gcn_hidden_size: 300
  dropout: 0.0
  enable_positional_encoding: False
  enable_gnn: True
  enable_lstm: True
  enable_link_state: True

# Training parameters
training:
  gpu: [1]
  n_epochs: 5
  batch_size: 1
  learning_rate: 0.0001
  num_workers: 2
  enable_val: False
  enable_dist: False