# YAML config for dataset, training, and model parameters

# Dataset parameters
dataset:
  n_flows_list: [20000]
  n_hosts_list: [3]
  shard: 0
  shard_list: [0,5000,5000] # [start, end, num]
  sample_list: [0,1,1] # [start, end, num]
  lr: 10
  bucket_thold: 1
  train_frac: 0.9
  enable_context: True
  topo_type: "_topo-pl-x_"

# Model parameters
model:
  model_name: "lstm"
  n_layer: 4
  loss_fn_type: "mse"
  hidden_dim: 10

# Training parameters
training:
  gpu: [3]
  n_epochs: 4
  batch_size: 2
  learning_rate: 0.0001
  num_workers: 1
  enable_val: True
  enable_dist: False