main: main.cpp TopologyBuilder.cpp Topology.cpp Device.cpp Link.cpp Chunk.cpp Event.cpp EventQueue.cpp EventList.cpp ../rdma_bench/mica/city.c
	g++ -O3 main.cpp TopologyBuilder.cpp Topology.cpp Device.cpp Link.cpp Chunk.cpp Event.cpp EventQueue.cpp EventList.cpp ../rdma_bench/mica/city.c -o main
